//! IRP major-function dispatch table for the ext4 FSD boundary.

use wdk_sys::{DRIVER_OBJECT, NTSTATUS, PDEVICE_OBJECT, PDRIVER_OBJECT, PIRP, STATUS_SUCCESS};

use crate::status::DriverError;

/// WDK major-function callback ABI generated by `wdk-sys`.
type DispatchRoutine = unsafe extern "C" fn(PDEVICE_OBJECT, PIRP) -> NTSTATUS;
/// WDK driver-unload callback ABI generated by `wdk-sys`.
type UnloadRoutine = unsafe extern "C" fn(PDRIVER_OBJECT);

/// Valid IRP major-function slot understood by this driver.
#[derive(Clone, Copy, Debug)]
struct MajorFunction {
    /// Index into `DRIVER_OBJECT::MajorFunction`.
    index: usize,
}

impl MajorFunction {
    /// Create/open request.
    const CREATE: Self = Self { index: 0x00 };
    /// Close request.
    const CLOSE: Self = Self { index: 0x02 };
    /// Read request.
    const READ: Self = Self { index: 0x03 };
    /// Write request.
    const WRITE: Self = Self { index: 0x04 };
    /// File information query.
    const QUERY_INFORMATION: Self = Self { index: 0x05 };
    /// File information mutation.
    const SET_INFORMATION: Self = Self { index: 0x06 };
    /// Volume information query.
    const QUERY_VOLUME_INFORMATION: Self = Self { index: 0x0A };
    /// Volume information mutation.
    const SET_VOLUME_INFORMATION: Self = Self { index: 0x0B };
    /// Directory enumeration request.
    const DIRECTORY_CONTROL: Self = Self { index: 0x0C };
    /// File-system control request.
    const FILE_SYSTEM_CONTROL: Self = Self { index: 0x0D };
    /// Device control request.
    const DEVICE_CONTROL: Self = Self { index: 0x0E };
    /// Shutdown notification.
    const SHUTDOWN: Self = Self { index: 0x10 };
    /// Cleanup request.
    const CLEANUP: Self = Self { index: 0x12 };
    /// Security descriptor query.
    const QUERY_SECURITY: Self = Self { index: 0x14 };
    /// Security descriptor mutation.
    const SET_SECURITY: Self = Self { index: 0x15 };

    /// Returns the WDK dispatch table index.
    const fn index(self) -> usize {
        self.index
    }
}

/// Dispatch table installation failed because the WDK table cannot hold a slot.
#[derive(Clone, Copy, Debug)]
pub(crate) struct DispatchInstallError;

/// Typed writer for the WDK major-function dispatch table.
struct DispatchTable<'driver> {
    /// Driver object whose dispatch table is being initialized.
    driver: &'driver mut DRIVER_OBJECT,
}

impl<'driver> DispatchTable<'driver> {
    /// Creates a dispatch-table writer for a driver object.
    fn new(driver: &'driver mut DRIVER_OBJECT) -> Self {
        Self { driver }
    }

    /// Installs the driver unload routine.
    fn unload(&mut self, routine: UnloadRoutine) {
        self.driver.DriverUnload = Some(routine);
    }

    /// Installs one major-function dispatch routine.
    fn set(
        &mut self,
        major_function: MajorFunction,
        routine: DispatchRoutine,
    ) -> Result<(), DispatchInstallError> {
        let Some(slot) = self.driver.MajorFunction.get_mut(major_function.index()) else {
            return Err(DispatchInstallError);
        };

        *slot = Some(routine);
        Ok(())
    }
}

/// Installs the ext4 file-system dispatch table.
pub(crate) fn install(driver: &mut DRIVER_OBJECT) -> Result<(), DispatchInstallError> {
    let mut table = DispatchTable::new(driver);
    table.unload(super::state::driver_unload);
    table.set(MajorFunction::CREATE, create)?;
    table.set(MajorFunction::CLOSE, success)?;
    table.set(MajorFunction::CLEANUP, success)?;
    table.set(MajorFunction::READ, read)?;
    table.set(MajorFunction::QUERY_INFORMATION, query_information)?;
    table.set(
        MajorFunction::QUERY_VOLUME_INFORMATION,
        query_volume_information,
    )?;
    table.set(MajorFunction::DIRECTORY_CONTROL, directory_control)?;
    table.set(MajorFunction::FILE_SYSTEM_CONTROL, file_system_control)?;
    table.set(MajorFunction::DEVICE_CONTROL, device_control)?;
    table.set(MajorFunction::SHUTDOWN, success)?;
    table.set(MajorFunction::QUERY_SECURITY, query_security)?;

    table.set(MajorFunction::WRITE, write)?;
    table.set(MajorFunction::SET_INFORMATION, set_information)?;
    table.set(
        MajorFunction::SET_VOLUME_INFORMATION,
        set_volume_information,
    )?;
    table.set(MajorFunction::SET_SECURITY, set_security)?;

    Ok(())
}

/// Handles create/open IRPs until namespace open state is implemented.
unsafe extern "C" fn create(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch_unimplemented(device, irp)
}

/// Handles read IRPs until file data reads are wired to mounted volumes.
unsafe extern "C" fn read(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch_unimplemented(device, irp)
}

/// Handles write IRPs until file data writes are wired to mounted volumes.
unsafe extern "C" fn write(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch_unimplemented(device, irp)
}

/// Handles file information queries until FCB-backed metadata exists.
unsafe extern "C" fn query_information(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch_unimplemented(device, irp)
}

/// Handles file information mutations until FCB-backed metadata updates exist.
unsafe extern "C" fn set_information(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch_unimplemented(device, irp)
}

/// Handles volume information queries until VCB state exists.
unsafe extern "C" fn query_volume_information(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch_unimplemented(device, irp)
}

/// Handles volume information mutations until VCB state updates exist.
unsafe extern "C" fn set_volume_information(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch_unimplemented(device, irp)
}

/// Handles directory enumeration until directory CCB state exists.
unsafe extern "C" fn directory_control(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch_unimplemented(device, irp)
}

/// Rejects unsupported file-system control requests.
unsafe extern "C" fn file_system_control(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    reject_invalid_device_request(device, irp)
}

/// Rejects unsupported device-control requests.
unsafe extern "C" fn device_control(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    reject_invalid_device_request(device, irp)
}

/// Rejects security descriptor queries until security projection exists.
unsafe extern "C" fn query_security(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    deny_access(device, irp)
}

/// Handles security descriptor mutations until POSIX descriptor projection exists.
unsafe extern "C" fn set_security(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch_unimplemented(device, irp)
}

/// Completes IRPs whose current minimal behavior is successful no-op.
unsafe extern "C" fn success(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    match decode_dispatch_target(device, irp) {
        Ok(()) => STATUS_SUCCESS,
        Err(error) => error.ntstatus(),
    }
}

/// Completes a decoded IRP as not implemented.
fn dispatch_unimplemented(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    match decode_dispatch_target(device, irp) {
        Ok(()) => DriverError::NotImplemented.ntstatus(),
        Err(error) => error.ntstatus(),
    }
}

/// Completes a decoded IRP as invalid for this device.
fn reject_invalid_device_request(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    match decode_dispatch_target(device, irp) {
        Ok(()) => DriverError::InvalidDeviceRequest.ntstatus(),
        Err(error) => error.ntstatus(),
    }
}

/// Completes a decoded IRP as access denied.
fn deny_access(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    match decode_dispatch_target(device, irp) {
        Ok(()) => DriverError::AccessDenied.ntstatus(),
        Err(error) => error.ntstatus(),
    }
}

/// Decodes the current dispatch boundary enough to reject null kernel inputs.
fn decode_dispatch_target(device: PDEVICE_OBJECT, irp: PIRP) -> Result<(), DriverError> {
    if device.is_null() || irp.is_null() {
        Err(DriverError::InvalidParameter)
    } else {
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use core::ffi::c_void;
    use core::ptr::NonNull;

    use wdk_sys::{
        PIRP, STATUS_INVALID_DEVICE_REQUEST, STATUS_INVALID_PARAMETER, STATUS_NOT_IMPLEMENTED,
    };

    use super::{dispatch_unimplemented, reject_invalid_device_request};

    /// Returns a non-null opaque pointer for decode-only dispatch tests.
    fn opaque<T>() -> *mut T {
        NonNull::<c_void>::dangling().as_ptr().cast()
    }

    #[test]
    fn null_dispatch_target_is_invalid_parameter() {
        assert_eq!(
            dispatch_unimplemented(core::ptr::null_mut(), opaque::<wdk_sys::IRP>()),
            STATUS_INVALID_PARAMETER
        );
        assert_eq!(
            dispatch_unimplemented(opaque::<wdk_sys::DEVICE_OBJECT>(), core::ptr::null_mut()),
            STATUS_INVALID_PARAMETER
        );
    }

    #[test]
    fn decoded_dispatch_target_preserves_handler_status() {
        let device = opaque::<wdk_sys::DEVICE_OBJECT>();
        let irp: PIRP = opaque::<wdk_sys::IRP>();

        assert_eq!(dispatch_unimplemented(device, irp), STATUS_NOT_IMPLEMENTED);
        assert_eq!(
            reject_invalid_device_request(device, irp),
            STATUS_INVALID_DEVICE_REQUEST
        );
    }
}
