//! IRP major-function dispatch table for the read-only FSD boundary.

use wdk_sys::{
    DRIVER_OBJECT, NTSTATUS, PDEVICE_OBJECT, PDRIVER_OBJECT, PIRP, STATUS_ACCESS_DENIED,
    STATUS_INVALID_DEVICE_REQUEST, STATUS_MEDIA_WRITE_PROTECTED, STATUS_NOT_IMPLEMENTED,
    STATUS_SUCCESS,
};

/// WDK major-function callback ABI generated by `wdk-sys`.
type DispatchRoutine = unsafe extern "C" fn(PDEVICE_OBJECT, PIRP) -> NTSTATUS;
/// WDK driver-unload callback ABI generated by `wdk-sys`.
type UnloadRoutine = unsafe extern "C" fn(PDRIVER_OBJECT);

/// Valid IRP major-function slot understood by this driver.
#[derive(Clone, Copy, Debug)]
struct MajorFunction {
    /// Index into `DRIVER_OBJECT::MajorFunction`.
    index: usize,
}

impl MajorFunction {
    /// Create/open request.
    const CREATE: Self = Self { index: 0x00 };
    /// Close request.
    const CLOSE: Self = Self { index: 0x02 };
    /// Read request.
    const READ: Self = Self { index: 0x03 };
    /// Write request.
    const WRITE: Self = Self { index: 0x04 };
    /// File information query.
    const QUERY_INFORMATION: Self = Self { index: 0x05 };
    /// File information mutation.
    const SET_INFORMATION: Self = Self { index: 0x06 };
    /// Volume information query.
    const QUERY_VOLUME_INFORMATION: Self = Self { index: 0x0A };
    /// Volume information mutation.
    const SET_VOLUME_INFORMATION: Self = Self { index: 0x0B };
    /// Directory enumeration request.
    const DIRECTORY_CONTROL: Self = Self { index: 0x0C };
    /// File-system control request.
    const FILE_SYSTEM_CONTROL: Self = Self { index: 0x0D };
    /// Device control request.
    const DEVICE_CONTROL: Self = Self { index: 0x0E };
    /// Shutdown notification.
    const SHUTDOWN: Self = Self { index: 0x10 };
    /// Cleanup request.
    const CLEANUP: Self = Self { index: 0x12 };
    /// Security descriptor query.
    const QUERY_SECURITY: Self = Self { index: 0x14 };
    /// Security descriptor mutation.
    const SET_SECURITY: Self = Self { index: 0x15 };

    /// Returns the WDK dispatch table index.
    const fn index(self) -> usize {
        self.index
    }
}

/// Dispatch table installation failed because the WDK table cannot hold a slot.
#[derive(Clone, Copy, Debug)]
pub(crate) struct DispatchInstallError;

/// Typed writer for the WDK major-function dispatch table.
struct DispatchTable<'driver> {
    /// Driver object whose dispatch table is being initialized.
    driver: &'driver mut DRIVER_OBJECT,
}

impl<'driver> DispatchTable<'driver> {
    /// Creates a dispatch-table writer for a driver object.
    fn new(driver: &'driver mut DRIVER_OBJECT) -> Self {
        Self { driver }
    }

    /// Installs the driver unload routine.
    fn unload(&mut self, routine: UnloadRoutine) {
        self.driver.DriverUnload = Some(routine);
    }

    /// Installs one major-function dispatch routine.
    fn set(
        &mut self,
        major_function: MajorFunction,
        routine: DispatchRoutine,
    ) -> Result<(), DispatchInstallError> {
        let Some(slot) = self.driver.MajorFunction.get_mut(major_function.index()) else {
            return Err(DispatchInstallError);
        };

        *slot = Some(routine);
        Ok(())
    }
}

/// Installs the v1 read-only dispatch table.
pub(crate) fn install(driver: &mut DRIVER_OBJECT) -> Result<(), DispatchInstallError> {
    let mut table = DispatchTable::new(driver);
    table.unload(super::state::driver_unload);
    table.set(MajorFunction::CREATE, create)?;
    table.set(MajorFunction::CLOSE, success)?;
    table.set(MajorFunction::CLEANUP, success)?;
    table.set(MajorFunction::READ, read)?;
    table.set(MajorFunction::QUERY_INFORMATION, query_information)?;
    table.set(
        MajorFunction::QUERY_VOLUME_INFORMATION,
        query_volume_information,
    )?;
    table.set(MajorFunction::DIRECTORY_CONTROL, directory_control)?;
    table.set(MajorFunction::FILE_SYSTEM_CONTROL, file_system_control)?;
    table.set(MajorFunction::DEVICE_CONTROL, device_control)?;
    table.set(MajorFunction::SHUTDOWN, success)?;
    table.set(MajorFunction::QUERY_SECURITY, query_security)?;

    table.set(MajorFunction::WRITE, read_only)?;
    table.set(MajorFunction::SET_INFORMATION, read_only)?;
    table.set(MajorFunction::SET_VOLUME_INFORMATION, read_only)?;
    table.set(MajorFunction::SET_SECURITY, read_only)?;

    Ok(())
}

/// Handles create/open IRPs until namespace open state is implemented.
unsafe extern "C" fn create(_device: PDEVICE_OBJECT, _irp: PIRP) -> NTSTATUS {
    STATUS_NOT_IMPLEMENTED
}

/// Handles read IRPs until file data reads are wired to mounted volumes.
unsafe extern "C" fn read(_device: PDEVICE_OBJECT, _irp: PIRP) -> NTSTATUS {
    STATUS_NOT_IMPLEMENTED
}

/// Handles file information queries until FCB-backed metadata exists.
unsafe extern "C" fn query_information(_device: PDEVICE_OBJECT, _irp: PIRP) -> NTSTATUS {
    STATUS_NOT_IMPLEMENTED
}

/// Handles volume information queries until VCB state exists.
unsafe extern "C" fn query_volume_information(_device: PDEVICE_OBJECT, _irp: PIRP) -> NTSTATUS {
    STATUS_NOT_IMPLEMENTED
}

/// Handles directory enumeration until directory CCB state exists.
unsafe extern "C" fn directory_control(_device: PDEVICE_OBJECT, _irp: PIRP) -> NTSTATUS {
    STATUS_NOT_IMPLEMENTED
}

/// Rejects unsupported file-system control requests.
unsafe extern "C" fn file_system_control(_device: PDEVICE_OBJECT, _irp: PIRP) -> NTSTATUS {
    STATUS_INVALID_DEVICE_REQUEST
}

/// Rejects unsupported device-control requests.
unsafe extern "C" fn device_control(_device: PDEVICE_OBJECT, _irp: PIRP) -> NTSTATUS {
    STATUS_INVALID_DEVICE_REQUEST
}

/// Rejects security descriptor queries until security projection exists.
unsafe extern "C" fn query_security(_device: PDEVICE_OBJECT, _irp: PIRP) -> NTSTATUS {
    STATUS_ACCESS_DENIED
}

/// Rejects mutation IRPs for the read-only driver boundary.
unsafe extern "C" fn read_only(_device: PDEVICE_OBJECT, _irp: PIRP) -> NTSTATUS {
    STATUS_MEDIA_WRITE_PROTECTED
}

/// Completes IRPs whose current minimal behavior is successful no-op.
unsafe extern "C" fn success(_device: PDEVICE_OBJECT, _irp: PIRP) -> NTSTATUS {
    STATUS_SUCCESS
}
