//! Native Windows kernel entry point for the ext4 file system driver.

#![feature(allocator_api)]
#![feature(try_reserve_kind)]
#![feature(vec_push_within_capacity)]
#![deny(unsafe_code)]
#![no_std]

extern crate alloc;
#[cfg(test)]
extern crate std;

mod irp;
mod kernel;
/// Generated control-device identity shared with the host lifecycle owner.
mod lifecycle_control {
    include!(concat!(env!("OUT_DIR"), "/lifecycle-control-v1.rs"));
}
mod memory;
mod request;
mod security_descriptor;
mod state;
mod wire;

#[cfg(not(test))]
use wdk_alloc::WdkAllocator;
use wdk_sys::{NTSTATUS, PCUNICODE_STRING, PDRIVER_OBJECT, STATUS_SUCCESS};

use crate::kernel::operational_trace::OperationalTraceRegistration;

/// Length of the fixed build identity record emitted by the build script.
const EXT4WIN_PRODUCTION_ARTIFACT_RECORD_LENGTH: usize =
    concat!("EXT4WIN_ARTIFACT_ID=", env!("EXT4WIN_ARTIFACT_ID")).len();

/// Build identity shared by the audited LLVM IR, link map, and signed PE image.
///
/// The build script forces this symbol into the linked image. Ordinary builds receive an
/// all-zero identity, which the production artifact gate rejects. Embedding the generated bytes
/// verbatim keeps the record at the symbol address so the link map can bind those exact bytes to
/// the signed image.
#[used]
#[expect(
    unsafe_code,
    reason = "the production artifact record must expose one stable linker-visible symbol"
)]
#[unsafe(no_mangle)]
static EXT4WIN_PRODUCTION_ARTIFACT_ID: [u8; EXT4WIN_PRODUCTION_ARTIFACT_RECORD_LENGTH] =
    *include_bytes!(concat!(env!("OUT_DIR"), "/artifact-identity.bin"));

#[cfg(not(test))]
#[global_allocator]
/// Kernel allocator used by WDK-backed driver builds.
static GLOBAL_ALLOCATOR: WdkAllocator = WdkAllocator;

/// Driver entry point called by the Windows kernel loader.
///
/// # Safety
/// The kernel must pass a valid `DRIVER_OBJECT` for the lifetime of this call.
#[expect(
    unsafe_code,
    reason = "DriverEntry is the audited Windows loader ABI and initial device-ownership boundary"
)]
#[unsafe(export_name = "DriverEntry")]
pub unsafe extern "system" fn driver_entry(
    driver: PDRIVER_OBJECT,
    _registry_path: PCUNICODE_STRING,
) -> NTSTATUS {
    let Some(driver_object) = (unsafe {
        // SAFETY: The kernel contract for DriverEntry provides a valid pointer
        // when loading the driver. Null is still handled defensively.
        driver.as_mut()
    }) else {
        return kernel::status::DriverError::InvalidParameter.ntstatus();
    };

    if request::dispatch::install(driver_object).is_err() {
        return kernel::status::DriverError::InvalidParameter.ntstatus();
    }

    let trace_registration = match OperationalTraceRegistration::register() {
        Ok(registration) => registration,
        Err(status) => return status,
    };
    let _control_device = match state::ControlDevice::create(driver, trace_registration.trace()) {
        Ok(control_device) => control_device,
        Err(status) => return status,
    };
    trace_registration.publish();

    STATUS_SUCCESS
}
