//! IRP major-function dispatch table for the ext4 FSD boundary.

use wdk_sys::{DRIVER_OBJECT, NTSTATUS, PDEVICE_OBJECT, PDRIVER_OBJECT, PIRP};

use crate::{
    irp::{
        DeviceExecutor, DirectoryControlMinorFunction, DispatchMajor, DispatchTarget,
        IrpCompletion, OwnedIrp, PreparedRequestKind, ReceivedIrp,
    },
    kernel::status::{DriverError, DriverResult},
};

/// WDK major-function callback ABI generated by `wdk-sys`.
type DispatchRoutine = unsafe extern "C" fn(PDEVICE_OBJECT, PIRP) -> NTSTATUS;
/// WDK driver-unload callback ABI generated by `wdk-sys`.
type UnloadRoutine = unsafe extern "C" fn(PDRIVER_OBJECT);

/// Dispatch table installation failed because the WDK table cannot hold a slot.
#[derive(Clone, Copy, Debug)]
pub(crate) struct DispatchInstallError;

/// Typed writer for the WDK major-function dispatch table.
struct DispatchTable<'driver> {
    /// Driver object whose dispatch table is being initialized.
    driver: &'driver mut DRIVER_OBJECT,
}

impl<'driver> DispatchTable<'driver> {
    /// Creates a dispatch-table writer for a driver object.
    fn new(driver: &'driver mut DRIVER_OBJECT) -> Self {
        Self { driver }
    }

    /// Installs the driver unload routine.
    fn unload(&mut self, routine: UnloadRoutine) {
        self.driver.DriverUnload = Some(routine);
    }

    /// Installs one major-function dispatch routine.
    /// # Errors
    ///
    /// Returns an error when `major_function` indexes outside `DRIVER_OBJECT::MajorFunction`.
    fn set(
        &mut self,
        major_function: DispatchMajor,
        routine: DispatchRoutine,
    ) -> Result<(), DispatchInstallError> {
        let Some(slot) = self
            .driver
            .MajorFunction
            .get_mut(major_function.table_index())
        else {
            return Err(DispatchInstallError);
        };

        *slot = Some(routine);
        Ok(())
    }
}

/// Installs the ext4 file-system dispatch table.
/// # Errors
///
/// Returns an error when the WDK dispatch table cannot hold one of ext4win's required IRP major
/// function slots.
pub(crate) fn install(driver: &mut DRIVER_OBJECT) -> Result<(), DispatchInstallError> {
    let mut table = DispatchTable::new(driver);
    table.unload(crate::state::driver_unload);
    table.set(DispatchMajor::Create, create)?;
    table.set(DispatchMajor::Close, close)?;
    table.set(DispatchMajor::Cleanup, cleanup)?;
    table.set(DispatchMajor::Read, read)?;
    table.set(DispatchMajor::FlushBuffers, flush_buffers)?;
    table.set(DispatchMajor::QueryInformation, query_information)?;
    table.set(
        DispatchMajor::QueryVolumeInformation,
        query_volume_information,
    )?;
    table.set(DispatchMajor::DirectoryControl, directory_control)?;
    table.set(DispatchMajor::FileSystemControl, file_system_control)?;
    table.set(DispatchMajor::DeviceControl, device_control)?;
    table.set(DispatchMajor::QueryEa, query_ea)?;
    table.set(DispatchMajor::SetEa, set_ea)?;
    table.set(DispatchMajor::LockControl, lock_control)?;
    table.set(DispatchMajor::Shutdown, shutdown)?;
    table.set(DispatchMajor::QuerySecurity, query_security)?;

    table.set(DispatchMajor::Write, write)?;
    table.set(DispatchMajor::SetInformation, set_information)?;
    table.set(DispatchMajor::SetVolumeInformation, set_volume_information)?;
    table.set(DispatchMajor::SetSecurity, set_security)?;

    Ok(())
}

/// Handles create/open IRPs.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active create/open dispatch call.
unsafe extern "C" fn create(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::Create)
}

/// Handles close IRPs.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active close dispatch call.
unsafe extern "C" fn close(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::Close)
}

/// Handles cleanup IRPs.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active cleanup dispatch call.
unsafe extern "C" fn cleanup(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::Cleanup)
}

/// Handles read IRPs.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active read dispatch call.
unsafe extern "C" fn read(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::Read)
}

/// Handles write IRPs.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active write dispatch call.
unsafe extern "C" fn write(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::Write)
}

/// Handles file information queries.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active file-information query.
unsafe extern "C" fn query_information(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::QueryInformation)
}

/// Handles file information mutations.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active file-information mutation.
unsafe extern "C" fn set_information(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::SetInformation)
}

/// Handles volume information queries.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active volume-information query.
unsafe extern "C" fn query_volume_information(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::QueryVolumeInformation)
}

/// Handles volume information mutations.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active volume-information mutation.
unsafe extern "C" fn set_volume_information(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::SetVolumeInformation)
}

/// Handles directory enumeration and change notification.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active directory-control dispatch.
unsafe extern "C" fn directory_control(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::DirectoryControl)
}

/// Handles file-system control requests.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active filesystem-control dispatch.
unsafe extern "C" fn file_system_control(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::FileSystemControl)
}

/// Rejects unsupported device-control requests.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active device-control dispatch.
unsafe extern "C" fn device_control(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::DeviceControl)
}

/// Handles security descriptor queries.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active security query.
unsafe extern "C" fn query_security(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::QuerySecurity)
}

/// Handles security descriptor mutations.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active security mutation.
unsafe extern "C" fn set_security(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::SetSecurity)
}

/// Handles flush requests.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active flush dispatch call.
unsafe extern "C" fn flush_buffers(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::FlushBuffers)
}

/// Handles extended-attribute queries.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active EA query.
unsafe extern "C" fn query_ea(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::QueryEa)
}

/// Handles extended-attribute mutations.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active EA mutation.
unsafe extern "C" fn set_ea(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::SetEa)
}

/// Handles byte-range lock requests.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active lock-control dispatch.
unsafe extern "C" fn lock_control(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::LockControl)
}

/// Handles shutdown notification.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active shutdown dispatch.
unsafe extern "C" fn shutdown(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    dispatch(device, irp, DispatchMajor::Shutdown)
}

/// Dispatches one IRP through the unified async-capable receive boundary.
fn dispatch(device: PDEVICE_OBJECT, irp: PIRP, major: DispatchMajor) -> NTSTATUS {
    let received = match ReceivedIrp::decode(device, irp) {
        Ok(received) => received,
        Err(error) => return ReceivedIrp::complete_decode_error(irp, error),
    };

    match dispatch_policy(major) {
        DispatchPolicy::Immediate => {
            let target = received.target();
            received.complete_result(execute_immediate(major, target))
        }
        DispatchPolicy::Queued => DeviceExecutor::receive(received, major),
        DispatchPolicy::SynchronousCleanup => dispatch_cleanup(received),
        DispatchPolicy::SynchronousClose => {
            let target = received.target();
            received.complete_result(crate::request::file_info::close(target))
        }
        DispatchPolicy::FsRtlFileLock => dispatch_file_lock(received),
    }
}

/// Queue policy for a received major function.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum DispatchPolicy {
    /// Complete during the dispatch callback.
    Immediate,
    /// Mark pending and execute from the device queue worker.
    Queued,
    /// Cancel pending IRPs and consume cleanup-owned state in the requestor thread.
    SynchronousCleanup,
    /// Release terminal FILE_OBJECT contexts synchronously, including post-create cancellation.
    SynchronousClose,
    /// Transfer terminal completion to the FsRtl byte-range lock package.
    FsRtlFileLock,
}

/// Returns the queue policy for a major function.
const fn dispatch_policy(major: DispatchMajor) -> DispatchPolicy {
    match major {
        DispatchMajor::DeviceControl => DispatchPolicy::Immediate,
        DispatchMajor::Cleanup => DispatchPolicy::SynchronousCleanup,
        DispatchMajor::Close => DispatchPolicy::SynchronousClose,
        DispatchMajor::LockControl => DispatchPolicy::FsRtlFileLock,
        DispatchMajor::Create
        | DispatchMajor::Read
        | DispatchMajor::Write
        | DispatchMajor::QueryInformation
        | DispatchMajor::SetInformation
        | DispatchMajor::QueryVolumeInformation
        | DispatchMajor::SetVolumeInformation
        | DispatchMajor::DirectoryControl
        | DispatchMajor::FileSystemControl
        | DispatchMajor::FlushBuffers
        | DispatchMajor::QueryEa
        | DispatchMajor::SetEa
        | DispatchMajor::QuerySecurity
        | DispatchMajor::SetSecurity
        | DispatchMajor::Shutdown => DispatchPolicy::Queued,
    }
}

/// Cancels queued IRPs for a FILE_OBJECT, then executes cleanup in the requestor thread.
fn dispatch_cleanup(received: ReceivedIrp) -> NTSTATUS {
    let target = received.target();
    let file_object = match target.current_stack().and_then(|stack| stack.file_object()) {
        Ok(file_object) => file_object,
        Err(error) => return received.complete_result(Err(error)),
    };
    if let Err(error) = DeviceExecutor::cancel_file_object(target.device(), file_object) {
        return received.complete_result(Err(error));
    }
    received.complete_result(crate::request::file_info::cleanup(target))
}

/// Decodes a lock target, then lets FsRtl own and complete the lock-control IRP.
fn dispatch_file_lock(received: ReceivedIrp) -> NTSTATUS {
    let target = received.target();
    match crate::request::file_info::lock_control(target) {
        Ok(opened_file) => received.delegate_byte_range_lock(opened_file.file_control_block()),
        Err(error) => received.complete_result(Err(error)),
    }
}

/// Executes and terminally completes or delegates one IRP owned by the device executor.
#[cfg_attr(
    test,
    expect(
        dead_code,
        reason = "kernel work-item worker is compiled out in unit tests"
    )
)]
pub(crate) async fn execute_owned(mut owned: OwnedIrp) {
    let prepared = owned.prepared_kind();
    let _status = match prepared {
        PreparedRequestKind::Major(DispatchMajor::Create) => {
            let result = crate::request::create::execute(owned.request()).await;
            owned.complete_create_result(result)
        }
        PreparedRequestKind::FileSystemControl(minor) => {
            let result = crate::request::file_system_control::execute(owned.request(), minor).await;
            owned.complete_result(result)
        }
        PreparedRequestKind::DirectoryControl(minor) => match minor {
            DirectoryControlMinorFunction::QueryDirectory => {
                let target = owned.target();
                owned.complete_result(crate::request::file_info::query_directory(target).await)
            }
            DirectoryControlMinorFunction::NotifyChangeDirectory => {
                crate::request::file_info::notify_change_directory(owned)
            }
            DirectoryControlMinorFunction::Unsupported => {
                owned.complete_result(Err(DriverError::InvalidDeviceRequest))
            }
        },
        PreparedRequestKind::Major(DispatchMajor::QuerySecurity) => {
            let result = crate::request::security::query(owned.request()).await;
            owned.complete_result(result)
        }
        PreparedRequestKind::Major(DispatchMajor::SetSecurity) => {
            let result = crate::request::security::set(owned.request()).await;
            owned.complete_result(result)
        }
        PreparedRequestKind::Major(major) => {
            let target = owned.target();
            owned.complete_result(execute_major(major, target).await)
        }
    };
}

/// Executes an immediate IRP during the dispatch callback.
/// # Errors
///
/// Returns an error when an immediate request cannot be decoded or is not valid for immediate
/// execution.
fn execute_immediate(major: DispatchMajor, target: DispatchTarget) -> DriverResult<IrpCompletion> {
    match major {
        DispatchMajor::DeviceControl => crate::request::file_system_control::device_control(target),
        DispatchMajor::Create
        | DispatchMajor::Close
        | DispatchMajor::Cleanup
        | DispatchMajor::Read
        | DispatchMajor::Write
        | DispatchMajor::QueryInformation
        | DispatchMajor::SetInformation
        | DispatchMajor::QueryVolumeInformation
        | DispatchMajor::SetVolumeInformation
        | DispatchMajor::DirectoryControl
        | DispatchMajor::FileSystemControl
        | DispatchMajor::FlushBuffers
        | DispatchMajor::QueryEa
        | DispatchMajor::SetEa
        | DispatchMajor::LockControl
        | DispatchMajor::QuerySecurity
        | DispatchMajor::SetSecurity
        | DispatchMajor::Shutdown => Err(DriverError::InvalidDeviceRequest),
    }
}

/// Executes the request implementation for a typed major function.
/// # Errors
///
/// Returns an error when the selected request implementation rejects the decoded IRP.
async fn execute_major(
    major: DispatchMajor,
    target: DispatchTarget,
) -> DriverResult<IrpCompletion> {
    match major {
        // Create has an ownership-bearing completion path selected by execute_owned.
        DispatchMajor::Create => Err(DriverError::InvalidDeviceRequest),
        // Lifecycle IRPs have a requester-thread-only execution boundary selected in `dispatch`.
        DispatchMajor::Close | DispatchMajor::Cleanup => Err(DriverError::InvalidDeviceRequest),
        DispatchMajor::Read => crate::request::file_info::read(target).await,
        DispatchMajor::Write => crate::request::file_info::write(target).await,
        DispatchMajor::QueryInformation => crate::request::file_info::query(target).await,
        DispatchMajor::SetInformation => crate::request::file_info::set(target).await,
        DispatchMajor::QueryVolumeInformation => crate::request::volume_info::query(target).await,
        DispatchMajor::SetVolumeInformation => crate::request::volume_info::set(target).await,
        // Directory control selects either normal completion or FsRtl ownership in execute_owned.
        DispatchMajor::DirectoryControl => Err(DriverError::InvalidDeviceRequest),
        // Mount retains a VPB lease and user FSCTLs share its ownership-bearing dispatch route.
        DispatchMajor::FileSystemControl => Err(DriverError::InvalidDeviceRequest),
        DispatchMajor::DeviceControl => Err(DriverError::InvalidDeviceRequest),
        DispatchMajor::FlushBuffers => crate::request::file_info::flush(target).await,
        DispatchMajor::QueryEa => crate::request::ea::query(target).await,
        DispatchMajor::SetEa => crate::request::ea::set(target).await,
        // Lock control is terminally delegated to FsRtl before generic execution.
        DispatchMajor::LockControl => Err(DriverError::InvalidDeviceRequest),
        DispatchMajor::Shutdown => crate::request::file_info::shutdown(target).await,
        // Security requests require requestor-context capture and are selected in execute_owned.
        DispatchMajor::QuerySecurity | DispatchMajor::SetSecurity => {
            Err(DriverError::InvalidDeviceRequest)
        }
    }
}

#[cfg(test)]
mod tests {
    use core::{
        future::Future,
        pin::pin,
        ptr::NonNull,
        task::{Context, Poll, Waker},
    };

    use crate::{
        irp::{DispatchMajor, DispatchTarget},
        kernel::status::DriverError,
    };

    use super::{DispatchPolicy, dispatch_policy, execute_major};

    /// Runs one continuation that is required to finish without lower I/O.
    fn run_ready<T>(future: impl Future<Output = T>) -> T {
        let mut future = pin!(future);
        let mut context = Context::from_waker(Waker::noop());
        match future.as_mut().poll(&mut context) {
            Poll::Ready(output) => output,
            Poll::Pending => {
                crate::kernel::fatal::KernelWideInconsistency::async_executor_state_corruption()
                    .bugcheck()
            }
        }
    }

    /// # Panics
    ///
    /// Panics when the shutdown request stops using the passive-level queue.
    #[test]
    fn shutdown_is_queued_for_passive_level_flush() {
        assert_eq!(
            dispatch_policy(DispatchMajor::Shutdown),
            DispatchPolicy::Queued
        );
    }

    /// # Panics
    ///
    /// Panics when lock-control IRPs stop being completed by FsRtl.
    #[test]
    fn lock_control_is_delegated_to_fsrtl() {
        assert_eq!(
            dispatch_policy(DispatchMajor::LockControl),
            DispatchPolicy::FsRtlFileLock
        );
    }

    /// # Panics
    ///
    /// Panics when cleanup leaves the requestor thread after cancelling its pending IRPs.
    #[test]
    fn cleanup_runs_synchronously_after_pending_irps_are_cancelled() {
        assert_eq!(
            dispatch_policy(DispatchMajor::Cleanup),
            DispatchPolicy::SynchronousCleanup
        );
    }

    /// # Panics
    ///
    /// Panics when close is queued behind a create whose completion can synchronously cancel it.
    #[test]
    fn close_runs_synchronously_for_post_create_cancellation() {
        assert_eq!(
            dispatch_policy(DispatchMajor::Close),
            DispatchPolicy::SynchronousClose
        );
    }

    /// # Panics
    ///
    /// Panics when create execution can re-enter the generic, ownership-free completion path.
    #[test]
    fn generic_major_execution_rejects_create() {
        let target = DispatchTarget::decode(
            NonNull::<wdk_sys::DEVICE_OBJECT>::dangling().as_ptr(),
            NonNull::<wdk_sys::IRP>::dangling().as_ptr(),
        );
        assert!(target.is_ok());
        if let Ok(target) = target {
            assert_eq!(
                run_ready(execute_major(DispatchMajor::Create, target)),
                Err(DriverError::InvalidDeviceRequest)
            );
        }
    }
}
