//! IRP major-function dispatch table for the ext4 FSD boundary.

use wdk_sys::{DRIVER_OBJECT, NTSTATUS, PDEVICE_OBJECT, PDRIVER_OBJECT, PIRP};

use crate::{
    irp::{
        ActorRequest, DataIoKind, DispatchMajor, IrpCompletion, OwnedIrp, PreparedDirectoryControl,
        PreparedRequest, ReceivedIrp,
    },
    kernel::status::{DriverError, DriverResult},
};

use super::operation::{
    AdmitOperationError, FlushRequestKind, ImmediateRequestKind, MutationRequestKind,
    ReadRequestKind,
};
use crate::irp::reactor::{
    AdmittedOperation, HandleOperationLane, OperationAdmission, PostCleanupRequest, ReactorTarget,
};
use crate::state::{DriverDeviceKind, HandleAdmissionState};

/// WDK major-function callback ABI generated by `wdk-sys`.
type DispatchRoutine = unsafe extern "C" fn(PDEVICE_OBJECT, PIRP) -> NTSTATUS;
/// WDK driver-unload callback ABI generated by `wdk-sys`.
type UnloadRoutine = unsafe extern "C" fn(PDRIVER_OBJECT);

/// Dispatch table installation failed because the WDK table cannot hold a slot.
#[derive(Clone, Copy, Debug)]
pub(crate) struct DispatchInstallError;

/// Typed writer for the WDK major-function dispatch table.
struct DispatchTable<'driver> {
    /// Driver object whose dispatch table is being initialized.
    driver: &'driver mut DRIVER_OBJECT,
}

impl<'driver> DispatchTable<'driver> {
    /// Creates a dispatch-table writer for a driver object.
    fn new(driver: &'driver mut DRIVER_OBJECT) -> Self {
        Self { driver }
    }

    /// Installs the driver unload routine.
    fn unload(&mut self, routine: UnloadRoutine) {
        self.driver.DriverUnload = Some(routine);
    }

    /// Installs one major-function dispatch routine.
    /// # Errors
    ///
    /// Returns an error when `major_function` indexes outside `DRIVER_OBJECT::MajorFunction`.
    fn set(
        &mut self,
        major_function: DispatchMajor,
        routine: DispatchRoutine,
    ) -> Result<(), DispatchInstallError> {
        let Some(slot) = self
            .driver
            .MajorFunction
            .get_mut(major_function.table_index())
        else {
            return Err(DispatchInstallError);
        };

        *slot = Some(routine);
        Ok(())
    }
}

/// Installs the ext4 file-system dispatch table.
/// # Errors
///
/// Returns an error when the WDK dispatch table cannot hold one of ext4win's required IRP major
/// function slots.
pub(crate) fn install(driver: &mut DRIVER_OBJECT) -> Result<(), DispatchInstallError> {
    let mut table = DispatchTable::new(driver);
    table.unload(crate::state::driver_unload);
    table.set(DispatchMajor::Create, create)?;
    table.set(DispatchMajor::Close, close)?;
    table.set(DispatchMajor::Cleanup, cleanup)?;
    table.set(DispatchMajor::Read, read)?;
    table.set(DispatchMajor::FlushBuffers, flush_buffers)?;
    table.set(DispatchMajor::QueryInformation, query_information)?;
    table.set(
        DispatchMajor::QueryVolumeInformation,
        query_volume_information,
    )?;
    table.set(DispatchMajor::DirectoryControl, directory_control)?;
    table.set(DispatchMajor::FileSystemControl, file_system_control)?;
    table.set(DispatchMajor::DeviceControl, device_control)?;
    table.set(DispatchMajor::QueryEa, query_ea)?;
    table.set(DispatchMajor::SetEa, set_ea)?;
    table.set(DispatchMajor::LockControl, lock_control)?;
    table.set(DispatchMajor::Shutdown, shutdown)?;
    table.set(DispatchMajor::QuerySecurity, query_security)?;

    table.set(DispatchMajor::Write, write)?;
    table.set(DispatchMajor::SetInformation, set_information)?;
    table.set(DispatchMajor::SetVolumeInformation, set_volume_information)?;
    table.set(DispatchMajor::SetSecurity, set_security)?;

    Ok(())
}

/// Handles create/open IRPs.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active create/open dispatch call.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn create(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active create dispatch objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::Create)
    }
}

/// Handles close IRPs.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active close dispatch call.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn close(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active close dispatch objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::Close)
    }
}

/// Handles cleanup IRPs.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active cleanup dispatch call.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn cleanup(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active cleanup dispatch objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::Cleanup)
    }
}

/// Handles read IRPs.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active read dispatch call.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn read(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active read dispatch objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::Read)
    }
}

/// Handles write IRPs.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active write dispatch call.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn write(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active write dispatch objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::Write)
    }
}

/// Handles file information queries.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active file-information query.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn query_information(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active query dispatch objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::QueryInformation)
    }
}

/// Handles file information mutations.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active file-information mutation.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn set_information(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active set dispatch objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::SetInformation)
    }
}

/// Handles volume information queries.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active volume-information query.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn query_volume_information(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active volume query objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::QueryVolumeInformation)
    }
}

/// Handles volume information mutations.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active volume-information mutation.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn set_volume_information(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active volume set objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::SetVolumeInformation)
    }
}

/// Handles directory enumeration and change notification.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active directory-control dispatch.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn directory_control(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active directory objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::DirectoryControl)
    }
}

/// Handles file-system control requests.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active filesystem-control dispatch.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn file_system_control(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active filesystem-control objects from the manager.
        dispatch(device, irp, DispatchMajor::FileSystemControl)
    }
}

/// Rejects unsupported device-control requests.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active device-control dispatch.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn device_control(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active device-control objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::DeviceControl)
    }
}

/// Handles security descriptor queries.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active security query.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn query_security(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active security query objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::QuerySecurity)
    }
}

/// Handles security descriptor mutations.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active security mutation.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn set_security(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active security set objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::SetSecurity)
    }
}

/// Handles flush requests.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active flush dispatch call.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn flush_buffers(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active flush dispatch objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::FlushBuffers)
    }
}

/// Handles extended-attribute queries.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active EA query.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn query_ea(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active EA query objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::QueryEa)
    }
}

/// Handles extended-attribute mutations.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active EA mutation.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn set_ea(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active EA set objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::SetEa)
    }
}

/// Handles byte-range lock requests.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active lock-control dispatch.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn lock_control(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active lock dispatch objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::LockControl)
    }
}

/// Handles shutdown notification.
///
/// # Safety
/// The I/O Manager must pass the DEVICE_OBJECT and IRP for the active shutdown dispatch.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe extern "C" fn shutdown(device: PDEVICE_OBJECT, irp: PIRP) -> NTSTATUS {
    unsafe {
        // SAFETY: This callback receives the active shutdown objects from the I/O Manager.
        dispatch(device, irp, DispatchMajor::Shutdown)
    }
}

/// Dispatches one IRP through the unified completion-driven receive boundary.
/// # Safety
///
/// `device` and `irp` must be the live objects supplied to the active callback for `major`.
#[expect(
    unsafe_code,
    reason = "this audited kernel or raw-memory item documents each unsafe operation with a local SAFETY invariant"
)]
unsafe fn dispatch(device: PDEVICE_OBJECT, irp: PIRP, major: DispatchMajor) -> NTSTATUS {
    let mut received = match unsafe {
        // SAFETY: The callback caller retains the WDK-provided device and IRP for this transition.
        ReceivedIrp::decode(device, irp)
    } {
        Ok(received) => received,
        Err(error) => {
            return unsafe {
                // SAFETY: The same callback contract retains a non-null IRP for error completion.
                ReceivedIrp::complete_decode_error(irp, error)
            };
        }
    };

    let device_kind = match crate::state::driver_device_kind(received.device()) {
        Ok(device_kind) => device_kind,
        Err(error) => return received.complete_result(Err(error)),
    };
    if device_kind == DriverDeviceKind::MountedVolume {
        let cache_boundary = match major {
            DispatchMajor::Read => received.with_active(super::file_info::dispatch_cached_read),
            DispatchMajor::Write => received.with_active(super::file_info::dispatch_cached_write),
            DispatchMajor::FlushBuffers => received
                .with_active(super::file_info::flush_cache_before_queued_flush)
                .map(|()| None),
            DispatchMajor::Cleanup | DispatchMajor::Close => received
                .with_active(super::file_info::uninitialize_cache_before_cleanup)
                .map(|()| None),
            DispatchMajor::Create
            | DispatchMajor::QueryInformation
            | DispatchMajor::SetInformation
            | DispatchMajor::QueryVolumeInformation
            | DispatchMajor::SetVolumeInformation
            | DispatchMajor::DirectoryControl
            | DispatchMajor::FileSystemControl
            | DispatchMajor::DeviceControl
            | DispatchMajor::QueryEa
            | DispatchMajor::SetEa
            | DispatchMajor::LockControl
            | DispatchMajor::Shutdown
            | DispatchMajor::QuerySecurity
            | DispatchMajor::SetSecurity => Ok(None),
        };
        match cache_boundary {
            Ok(Some(completion)) => return received.complete(completion),
            Ok(None) => {}
            Err(error) => return received.complete_result(Err(error)),
        }
    }
    match dispatch_policy(device_kind, major) {
        DispatchPolicy::Immediate(request) => execute_immediate(received, request),
        DispatchPolicy::Queued => crate::state::queue_device_request(received, major),
        DispatchPolicy::FsRtlFileLock => dispatch_file_lock(received),
    }
}

/// Immediate request semantics selected from both the device kind and IRP major function.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum ImmediateDispatch {
    /// Establishes an uncontextualized handle to the secured control device.
    OpenControl,
    /// Releases per-handle control cleanup state; no such state is retained.
    CleanupControl,
    /// Releases one control FILE_OBJECT; no driver context is attached.
    CloseControl,
    /// Decodes the one private lifecycle request accepted by the control device.
    ControlDeviceRequest,
    /// Completes an unsupported request without entering a device actor.
    Reject,
}

/// Queue policy for a received major function.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum DispatchPolicy {
    /// Complete one explicitly selected request during the dispatch callback.
    Immediate(ImmediateDispatch),
    /// Mark pending and execute on the dedicated device actor.
    Queued,
    /// Transfer terminal completion to the FsRtl byte-range lock package.
    FsRtlFileLock,
}

/// Returns the queue policy for a major function.
const fn dispatch_policy(device_kind: DriverDeviceKind, major: DispatchMajor) -> DispatchPolicy {
    match device_kind {
        DriverDeviceKind::Control => match major {
            DispatchMajor::Create => DispatchPolicy::Immediate(ImmediateDispatch::OpenControl),
            DispatchMajor::Cleanup => DispatchPolicy::Immediate(ImmediateDispatch::CleanupControl),
            DispatchMajor::Close => DispatchPolicy::Immediate(ImmediateDispatch::CloseControl),
            DispatchMajor::DeviceControl => {
                DispatchPolicy::Immediate(ImmediateDispatch::ControlDeviceRequest)
            }
            DispatchMajor::FileSystemControl => DispatchPolicy::Queued,
            DispatchMajor::Read
            | DispatchMajor::Write
            | DispatchMajor::QueryInformation
            | DispatchMajor::SetInformation
            | DispatchMajor::QueryVolumeInformation
            | DispatchMajor::SetVolumeInformation
            | DispatchMajor::DirectoryControl
            | DispatchMajor::FlushBuffers
            | DispatchMajor::QueryEa
            | DispatchMajor::SetEa
            | DispatchMajor::LockControl
            | DispatchMajor::Shutdown
            | DispatchMajor::QuerySecurity
            | DispatchMajor::SetSecurity => DispatchPolicy::Immediate(ImmediateDispatch::Reject),
        },
        DriverDeviceKind::MountedVolume => match major {
            DispatchMajor::DeviceControl => DispatchPolicy::Immediate(ImmediateDispatch::Reject),
            DispatchMajor::LockControl => DispatchPolicy::FsRtlFileLock,
            DispatchMajor::Create
            | DispatchMajor::Cleanup
            | DispatchMajor::Close
            | DispatchMajor::Read
            | DispatchMajor::Write
            | DispatchMajor::QueryInformation
            | DispatchMajor::SetInformation
            | DispatchMajor::QueryVolumeInformation
            | DispatchMajor::SetVolumeInformation
            | DispatchMajor::DirectoryControl
            | DispatchMajor::FileSystemControl
            | DispatchMajor::FlushBuffers
            | DispatchMajor::QueryEa
            | DispatchMajor::SetEa
            | DispatchMajor::QuerySecurity
            | DispatchMajor::SetSecurity
            | DispatchMajor::Shutdown => DispatchPolicy::Queued,
        },
    }
}

/// Decodes a lock target, then lets FsRtl own and complete the lock-control IRP.
fn dispatch_file_lock(mut received: ReceivedIrp) -> NTSTATUS {
    match received.with_active(crate::request::file_info::lock_control) {
        Ok(file_control_block) => received.delegate_byte_range_lock(file_control_block),
        Err(error) => received.complete_result(Err(error)),
    }
}

/// Executes one immediate control-device or rejection transition and completes its IRP.
fn execute_immediate(mut received: ReceivedIrp, request: ImmediateDispatch) -> NTSTATUS {
    let result = match request {
        ImmediateDispatch::OpenControl
        | ImmediateDispatch::CleanupControl
        | ImmediateDispatch::CloseControl => Ok(IrpCompletion::EMPTY),
        ImmediateDispatch::ControlDeviceRequest => {
            let stack = received.with_active(|active| active.current_stack()?.device_control());
            stack.and_then(|stack| {
                if !stack.is_payload_free() {
                    return Err(DriverError::InvalidParameter);
                }
                if stack.io_control_code() != crate::lifecycle_control::PREPARE_UNLOAD_IOCTL {
                    return Err(DriverError::InvalidDeviceRequest);
                }
                crate::state::ControlDevice::prepare_unload(received.device())?;
                Ok(IrpCompletion::EMPTY)
            })
        }
        ImmediateDispatch::Reject => Err(DriverError::InvalidDeviceRequest),
    };
    received.complete_result(result)
}

/// Selects the scheduler lane shared by requests that remain legal across CLEANUP.
/// # Errors
///
/// Returns `FileClosed` after CLOSE has begun consuming the handle lane.
fn post_cleanup_lane(
    state: HandleAdmissionState,
    request: PostCleanupRequest,
) -> DriverResult<HandleOperationLane> {
    match state {
        HandleAdmissionState::OpenHandle
        | HandleAdmissionState::CleanupDraining
        | HandleAdmissionState::CleanedHandle => Ok(HandleOperationLane::PostCleanup(request)),
        HandleAdmissionState::ClosingHandle | HandleAdmissionState::ClosedHandle => {
            Err(DriverError::FileClosed)
        }
    }
}

/// Converts one CSQ-owned request into a concrete consuming operation.
///
/// Classification is copied out before `owned` moves so no pointer into queue metadata can enter
/// an operation or lower completion envelope.
/// # Errors
///
/// Returns the still-owned IRP when lifecycle admission, request decoding, operation allocation,
/// or mounted-state validation fails.
pub(crate) fn admit_owned(
    mut owned: OwnedIrp,
    target: &mut ReactorTarget,
) -> Result<AdmittedOperation, AdmitOperationError> {
    #[derive(Clone, Copy, Debug, Eq, PartialEq)]
    enum HandleRequestClass {
        Device,
        Ordinary,
        PagingRead,
        PagingWrite,
        FlushBuffers,
        Cleanup,
        Close,
    }

    enum LifecyclePublication {
        None,
        Cleanup(crate::state::PreparedHandleAdmission),
        Close(crate::state::PreparedHandleAdmission),
    }

    enum Admission {
        Mount(super::file_system_control::MountAdmission),
        Read(ReadRequestKind),
        Mutation(MutationRequestKind),
        Flush(FlushRequestKind),
        Immediate(ImmediateRequestKind),
        Notification,
        VolumeControl(super::operation::VolumeControlRequestKind),
        FsControl(crate::irp::FileSystemControlMinorFunction),
        Unsupported,
    }

    let admission = match owned.actor_request() {
        ActorRequest::Captured(PreparedRequest::Read(_)) => Admission::Read(ReadRequestKind::Read),
        ActorRequest::Captured(PreparedRequest::QueryInformation) => {
            Admission::Read(ReadRequestKind::QueryInformation)
        }
        ActorRequest::Captured(PreparedRequest::DirectoryControl(
            PreparedDirectoryControl::QueryDirectory(_),
        )) => Admission::Read(ReadRequestKind::QueryDirectory),
        ActorRequest::Captured(PreparedRequest::QueryEa(_)) => {
            Admission::Read(ReadRequestKind::QueryEa)
        }
        ActorRequest::Captured(PreparedRequest::QuerySecurity { .. }) => {
            Admission::Read(ReadRequestKind::QuerySecurity)
        }
        ActorRequest::Captured(PreparedRequest::QueryVolumeInformation) => {
            Admission::Immediate(ImmediateRequestKind::QueryVolumeInformation)
        }
        ActorRequest::Captured(PreparedRequest::Create) => {
            Admission::Mutation(MutationRequestKind::Create)
        }
        ActorRequest::Captured(PreparedRequest::Write(_)) => {
            Admission::Mutation(MutationRequestKind::Write)
        }
        ActorRequest::Captured(PreparedRequest::SetInformation) => {
            Admission::Mutation(MutationRequestKind::SetInformation)
        }
        ActorRequest::Captured(PreparedRequest::SetEa) => {
            Admission::Mutation(MutationRequestKind::SetEa)
        }
        ActorRequest::Captured(PreparedRequest::SetSecurity { .. }) => {
            Admission::Mutation(MutationRequestKind::SetSecurity)
        }
        ActorRequest::Captured(PreparedRequest::SetVolumeInformation) => {
            Admission::Mutation(MutationRequestKind::SetVolumeInformation)
        }
        ActorRequest::Cleanup => Admission::Mutation(MutationRequestKind::Cleanup),
        ActorRequest::Captured(PreparedRequest::FlushBuffers) => {
            Admission::Flush(FlushRequestKind::FlushBuffers)
        }
        ActorRequest::Captured(PreparedRequest::Shutdown) => {
            Admission::Flush(FlushRequestKind::Shutdown)
        }
        ActorRequest::Close => Admission::Immediate(ImmediateRequestKind::Close),
        ActorRequest::Captured(PreparedRequest::DirectoryControl(
            PreparedDirectoryControl::NotifyChangeDirectory,
        )) => Admission::Notification,
        ActorRequest::Captured(PreparedRequest::FileSystemControl(minor)) => {
            Admission::FsControl(*minor)
        }
    };

    let admission = match admission {
        Admission::FsControl(minor) => {
            let classified = match super::file_system_control::classify(owned.request(), minor) {
                Ok(classified) => classified,
                Err(error) => return Err(AdmitOperationError::new(error, owned)),
            };
            match classified {
                super::file_system_control::FsControlAdmission::Mount(mount) => {
                    Admission::Mount(mount)
                }
                super::file_system_control::FsControlAdmission::Unsupported => {
                    Admission::Unsupported
                }
                super::file_system_control::FsControlAdmission::User(code) => match code {
                    crate::irp::FsControlCode::GetReparsePoint => {
                        Admission::Read(ReadRequestKind::GetReparsePoint)
                    }
                    crate::irp::FsControlCode::SetReparsePoint => {
                        Admission::Mutation(MutationRequestKind::SetReparsePoint)
                    }
                    crate::irp::FsControlCode::DeleteReparsePoint => {
                        Admission::Mutation(MutationRequestKind::DeleteReparsePoint)
                    }
                    crate::irp::FsControlCode::EnableVerity => {
                        Admission::Mutation(MutationRequestKind::EnableVerity)
                    }
                    crate::irp::FsControlCode::AddEncryptionKey => {
                        Admission::Mutation(MutationRequestKind::AddEncryptionKey)
                    }
                    crate::irp::FsControlCode::RemoveEncryptionKey => {
                        Admission::Mutation(MutationRequestKind::RemoveEncryptionKey)
                    }
                    crate::irp::FsControlCode::GetEncryptionKeyStatus => {
                        Admission::Immediate(ImmediateRequestKind::GetEncryptionKeyStatus)
                    }
                    crate::irp::FsControlCode::LockVolume => {
                        Admission::VolumeControl(super::operation::VolumeControlRequestKind::Lock)
                    }
                    crate::irp::FsControlCode::UnlockVolume => {
                        Admission::VolumeControl(super::operation::VolumeControlRequestKind::Unlock)
                    }
                    crate::irp::FsControlCode::DismountVolume => Admission::VolumeControl(
                        super::operation::VolumeControlRequestKind::Dismount,
                    ),
                    crate::irp::FsControlCode::IsVolumeMounted => Admission::VolumeControl(
                        super::operation::VolumeControlRequestKind::IsMounted,
                    ),
                },
            }
        }
        admission => admission,
    };

    let data_io_kind = match owned.actor_request() {
        ActorRequest::Captured(PreparedRequest::Read(read)) => Some(read.kind()),
        ActorRequest::Captured(PreparedRequest::Write(write)) => Some(write.kind()),
        _ => None,
    };
    let handle_class = match &admission {
        Admission::Mount(_) => HandleRequestClass::Device,
        Admission::Read(ReadRequestKind::Read) if data_io_kind == Some(DataIoKind::Paging) => {
            HandleRequestClass::PagingRead
        }
        Admission::Read(_) => HandleRequestClass::Ordinary,
        Admission::Mutation(MutationRequestKind::Create) => HandleRequestClass::Device,
        Admission::Mutation(MutationRequestKind::Write)
            if data_io_kind == Some(DataIoKind::Paging) =>
        {
            HandleRequestClass::PagingWrite
        }
        Admission::Mutation(MutationRequestKind::Cleanup) => HandleRequestClass::Cleanup,
        Admission::Mutation(_) => HandleRequestClass::Ordinary,
        Admission::Flush(FlushRequestKind::FlushBuffers) => HandleRequestClass::FlushBuffers,
        Admission::Flush(FlushRequestKind::Shutdown) => HandleRequestClass::Device,
        Admission::Immediate(ImmediateRequestKind::Close) => HandleRequestClass::Close,
        Admission::Immediate(_) | Admission::Notification | Admission::VolumeControl(_) => {
            HandleRequestClass::Ordinary
        }
        Admission::FsControl(_) | Admission::Unsupported => HandleRequestClass::Device,
    };

    let (operation_admission, lifecycle_publication) = if handle_class == HandleRequestClass::Device
    {
        (OperationAdmission::Device, LifecyclePublication::None)
    } else {
        let prepared = match super::file_info::prepare_handle_admission(owned.request()) {
            Ok(prepared) => prepared,
            Err(error) => return Err(AdmitOperationError::new(error, owned)),
        };
        match prepared {
            None if handle_class == HandleRequestClass::Close => {
                (OperationAdmission::Device, LifecyclePublication::None)
            }
            None => {
                return Err(AdmitOperationError::new(
                    DriverError::InvalidParameter,
                    owned,
                ));
            }
            Some(prepared) => {
                let file_object = prepared.file_object();
                let state = prepared.state();
                match handle_class {
                    HandleRequestClass::Ordinary => {
                        if state != HandleAdmissionState::OpenHandle {
                            return Err(AdmitOperationError::new(DriverError::FileClosed, owned));
                        }
                        (
                            OperationAdmission::Handle {
                                file_object,
                                lane: HandleOperationLane::Ordinary,
                            },
                            LifecyclePublication::None,
                        )
                    }
                    HandleRequestClass::PagingRead | HandleRequestClass::PagingWrite => {
                        let request = if handle_class == HandleRequestClass::PagingRead {
                            PostCleanupRequest::PagingRead
                        } else {
                            PostCleanupRequest::PagingWrite
                        };
                        let lane = match post_cleanup_lane(state, request) {
                            Ok(lane) => lane,
                            Err(error) => return Err(AdmitOperationError::new(error, owned)),
                        };
                        (
                            OperationAdmission::Handle { file_object, lane },
                            LifecyclePublication::None,
                        )
                    }
                    HandleRequestClass::FlushBuffers => {
                        let lane = match post_cleanup_lane(state, PostCleanupRequest::FlushBuffers)
                        {
                            Ok(lane) => lane,
                            Err(error) => return Err(AdmitOperationError::new(error, owned)),
                        };
                        (
                            OperationAdmission::Handle { file_object, lane },
                            LifecyclePublication::None,
                        )
                    }
                    HandleRequestClass::Cleanup => {
                        if !matches!(
                            state,
                            HandleAdmissionState::OpenHandle
                                | HandleAdmissionState::CleanupDraining
                        ) {
                            return Err(AdmitOperationError::new(DriverError::FileClosed, owned));
                        }
                        (
                            OperationAdmission::Handle {
                                file_object,
                                lane: HandleOperationLane::Cleanup,
                            },
                            LifecyclePublication::Cleanup(prepared),
                        )
                    }
                    HandleRequestClass::Close => (
                        OperationAdmission::Handle {
                            file_object,
                            lane: HandleOperationLane::PostCleanup(PostCleanupRequest::Close),
                        },
                        LifecyclePublication::Close(prepared),
                    ),
                    HandleRequestClass::Device => {
                        (OperationAdmission::Device, LifecyclePublication::None)
                    }
                }
            }
        }
    };

    let operation = match admission {
        Admission::Mount(admission) => {
            target.require_control_device();
            super::operation::mount(owned, admission)
        }
        Admission::Read(kind) => {
            target.with_mounted_access(|access| super::operation::read(owned, kind, access))
        }
        Admission::Mutation(kind) => {
            target.with_mounted_access(|access| super::operation::mutation(owned, kind, access))
        }
        Admission::Flush(kind) => {
            target.with_mounted_access(|access| super::operation::flush(owned, kind, access))
        }
        Admission::Immediate(kind) => {
            target.with_mounted_access(|_| super::operation::immediate(owned, kind))
        }
        Admission::Notification => {
            target.with_mounted_access(|_| super::operation::notification(owned))
        }
        Admission::VolumeControl(kind) => {
            target.with_mounted_access(|_| super::operation::volume_control(owned, kind))
        }
        Admission::FsControl(_) => Err(AdmitOperationError::new(
            DriverError::InternalInvariantViolation,
            owned,
        )),
        Admission::Unsupported => Err(AdmitOperationError::new(
            DriverError::InvalidDeviceRequest,
            owned,
        )),
    }?;
    match lifecycle_publication {
        LifecyclePublication::None => {}
        LifecyclePublication::Cleanup(prepared) => prepared.begin_cleanup(),
        LifecyclePublication::Close(prepared) => prepared.begin_close(),
    }
    Ok(AdmittedOperation::new(operation, operation_admission))
}

#[cfg(test)]
mod tests {
    use crate::{
        irp::{
            DispatchMajor,
            reactor::{HandleOperationLane, PostCleanupRequest},
        },
        kernel::status::DriverError,
        state::{DriverDeviceKind, HandleAdmissionState},
    };

    use super::{DispatchPolicy, ImmediateDispatch, dispatch_policy, post_cleanup_lane};

    /// Keeps the production operation-construction graph inside the unit-test reachability set.
    ///
    /// # Panics
    ///
    /// This test has no runtime failure path. Compilation fails if the concrete admission boundary
    /// is removed or changes into a compatibility facade.
    #[test]
    fn operation_admission_boundary_remains_linked() {
        let boundary = super::admit_owned;
        let _ = boundary;
    }

    /// # Panics
    ///
    /// Panics when the shutdown request stops using the passive-level queue.
    #[test]
    fn shutdown_is_queued_for_passive_level_flush() {
        assert_eq!(
            dispatch_policy(DriverDeviceKind::MountedVolume, DispatchMajor::Shutdown),
            DispatchPolicy::Queued
        );
    }

    /// # Panics
    ///
    /// Panics when lock-control IRPs stop being completed by FsRtl.
    #[test]
    fn lock_control_is_delegated_to_fsrtl() {
        assert_eq!(
            dispatch_policy(DriverDeviceKind::MountedVolume, DispatchMajor::LockControl),
            DispatchPolicy::FsRtlFileLock
        );
    }

    /// # Panics
    ///
    /// Panics when cleanup stops using the actor barrier after cancelling earlier pending IRPs.
    #[test]
    fn cleanup_runs_on_actor_after_pending_irps_are_cancelled() {
        assert_eq!(
            dispatch_policy(DriverDeviceKind::MountedVolume, DispatchMajor::Cleanup),
            DispatchPolicy::Queued
        );
    }

    /// # Panics
    ///
    /// Panics when close stops following create and cleanup on the same actor.
    #[test]
    fn close_runs_after_prior_file_object_operations() {
        assert_eq!(
            dispatch_policy(DriverDeviceKind::MountedVolume, DispatchMajor::Close),
            DispatchPolicy::Queued
        );
    }

    /// # Panics
    ///
    /// Panics when the named control device enters mounted-volume handle machinery or admits a
    /// lifecycle request through the reactor it is responsible for stopping.
    #[test]
    fn control_device_lifecycle_requests_are_immediate_and_mounts_remain_queued() {
        assert_eq!(
            dispatch_policy(DriverDeviceKind::Control, DispatchMajor::Create),
            DispatchPolicy::Immediate(ImmediateDispatch::OpenControl)
        );
        assert_eq!(
            dispatch_policy(DriverDeviceKind::Control, DispatchMajor::Cleanup),
            DispatchPolicy::Immediate(ImmediateDispatch::CleanupControl)
        );
        assert_eq!(
            dispatch_policy(DriverDeviceKind::Control, DispatchMajor::Close),
            DispatchPolicy::Immediate(ImmediateDispatch::CloseControl)
        );
        assert_eq!(
            dispatch_policy(DriverDeviceKind::Control, DispatchMajor::DeviceControl),
            DispatchPolicy::Immediate(ImmediateDispatch::ControlDeviceRequest)
        );
        assert_eq!(
            dispatch_policy(DriverDeviceKind::Control, DispatchMajor::FileSystemControl),
            DispatchPolicy::Queued
        );
        assert_eq!(
            dispatch_policy(DriverDeviceKind::Control, DispatchMajor::Read),
            DispatchPolicy::Immediate(ImmediateDispatch::Reject)
        );
    }

    /// # Panics
    ///
    /// Panics when paging I/O or flush loses its post-cleanup lane while the handle is open, or
    /// remains admissible after close begins.
    #[test]
    fn post_cleanup_requests_keep_one_lane_for_the_whole_live_handle() {
        for request in [
            PostCleanupRequest::PagingRead,
            PostCleanupRequest::PagingWrite,
            PostCleanupRequest::FlushBuffers,
        ] {
            for state in [
                HandleAdmissionState::OpenHandle,
                HandleAdmissionState::CleanupDraining,
                HandleAdmissionState::CleanedHandle,
            ] {
                assert!(matches!(
                    post_cleanup_lane(state, request),
                    Ok(HandleOperationLane::PostCleanup(observed)) if observed == request
                ));
            }
            for state in [
                HandleAdmissionState::ClosingHandle,
                HandleAdmissionState::ClosedHandle,
            ] {
                assert!(matches!(
                    post_cleanup_lane(state, request),
                    Err(DriverError::FileClosed)
                ));
            }
        }
    }
}
